a = input("coefficient of x^2?")
a = float(a)
b = input("coefficient of x?")
b = float(b)
c = input("coefficient of x^0?")
c = float(c)
x1 = (-b+(((b**2)-4*a*c)**0.5))/(2*a)
x2 = (-b-(((b**2)-4*a*c)**0.5))/(2*a)
print(x1,x2)